version: '3'
services:
  xen-orchestra:
    restart: unless-stopped
    image: mkoetter/xen-orchestra:latest
    container_name: xen-orchestra
    privileged: true
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - XO_HTTP_PORT=8080
  redis:
    restart: unless-stopped
    container_name: xen-orchestra-redis
    image: redis:6
    command: redis-server --appendonly yes
    volumes:
        - redis-data:/data
volumes:
  redis-data:
