version: '3'
services:
  xen-orchestra:
    restart: unless-stopped
    image: mkoetter/xen-orchestra:latest
    platform: linux/amd64
    container_name: xen-orchestra
    # This might cause startup issues, see: https://github.com/michaelkoetter/xen-orchestra-daily/issues/40
    #privileged: true
    cap_add:
      - SYS_ADMIN
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - XO_SERVER_HTTP_PORT=8080
  redis:
    restart: unless-stopped
    container_name: xen-orchestra-redis
    image: redis:7
    platform: linux/amd64
    command: redis-server --appendonly yes
    volumes:
        - redis-data:/data
volumes:
  redis-data:
