version: '3'
services:
  xen-orchestra:
    restart: unless-stopped
    image: mkoetter/xen-orchestra:latest
    platform: linux/amd64
    container_name: xen-orchestra
    cap_add:
      - SYS_ADMIN
    ports:
      - "80:80"
    depends_on:
      - redis

  redis:
    restart: unless-stopped
    container_name: xen-orchestra-redis
    image: redis:7
    platform: linux/amd64
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data

volumes:
  redis-data:
