#!/bin/bash

mkdir -p /etc/{xo-server,xo-proxy}

(envsubst <<EOF
[[http.listen]]
port = 80
[redis]
uri = '$XO_SERVER_REDIS_URI'
EOF
) > /etc/xo-server/config.toml

(envsubst <<EOF
authenticationToken = '$XO_PROXY_AUTHENTICATION_TOKEN'
EOF
) > /etc/xo-proxy/config.toml

if [ "$XO_PROXY_ENABLED" == "1" ]
then
    if [ -z $XO_PROXY_AUTHENTICATION_TOKEN ]
    then
        echo "*** FATAL: XO_PROXY_AUTHENTICATION_TOKEN is not set!"
        exit 1
    fi
    echo "*** Starting XenOrchestra Proxy ..."
    exec /xen-orchestra/@xen-orchestra/proxy/index.mjs $@
else 
    echo "*** Starting XenOrchestra Server ..."
    exec /xen-orchestra/packages/xo-server/dist/cli.mjs $@
fi
