name: Build Docker Image

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    paths-ignore:
      - README.md
      - docker-compose.yml

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Get xo-server version
        id: xo-version
        run: |
          echo "XO_VERSION=$(cat ./packages/xo-server/package.json | jq -r .version)" >> $GITHUB_ENV

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3.6.2
        with:
          images: mkoetter/xen-orchestra
          flavor: |
            latest=true
          tags: |
            type=edge
            type=schedule,pattern={{date 'YYYYMMDD'}}
            type=raw,v${{ env.XO_VERSION }}
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.2.0
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2.8.0
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
